database:
  dialect: mysql
  host: 172.16.15.41
  port: 18806
  dbname: fsserver
  username: root
  #password: CsRd_#2018#@
  password: Arcvideo@01
  migration: false

task:
  keepTask: true

aiAddress: http://172.16.15.17:18500